### ISSUE TITLE
Create group name issue

### ISSUE THREAD

**Issue by Shinmi** [mesibo/mesiboframeworks#10]
Hi mesibo, I'm using the latest SDK 1.8.7 mesibo iOS, I have a problem when creating a group, my name group is not created.
this my code
```
MesiboManager.shared().startMesibo()
        let setting = MesiboGroupSettings()
        setting.name = name
        setting.videoResolution = UInt32(MESIBO_RESOLUTION_VGA)
        setting.callFlags = UInt32(MESIBO_GROUPCALLFLAG_AUDIO | MESIBO_GROUPCALLFLAG_VIDEO | MESIBO_GROUPCALLFLAG_SCREEN | MESIBO_GROUPCALLFLAG_FIXEDRESOLUTION)
        setting.flags = UInt32(MESIBO_FLAG_DEFAULT)
        mesiboInstance?.createGroup(setting, listener: self)
```
the group name should be `testing grup` but it create `Group 124116`, it group id it self created as group name

**Comment by mesibo** [comment]
Post full code where you are checking the group name.

**Comment by mesibo** [comment]
Thanks for reporting this, there was a minor issue for ios. It is fixed now. Please try and let us know.
