### ISSUE TITLE
Cannot delete group or remove member 

### ISSUE THREAD

**Issue by Shinmi** [mesibo/mesiboframeworks#11]
Hi Mesibo,
I'm using latest SDK iOS 1.8.10, I follow your documentation about remove member or delete group. 
 ```
func removeGroup(groupProfiles: MesiboGroupProfile) {
        groupProfiles.canRemoveGroup()
        groupProfiles.deleteGroup()
        groupProfiles.save()
}
```
the group still exist in group list. I'm using this  code `let list = mesiboInstance?.getSortedProfiles() as? [MesiboProfile]` to get group list. 
I check group tab on mesibo console, the group I want to delete is not deleted. Is there my method to delete group was wrong implementation?

**Comment by Shinmi** [comment]
from my last issue, I found admin can delete and remove member. So I get the group profile from `let groupProfile = mesiboInstance?.getProfile(addressId, groupid: groupProfiles!.getGroupId())` 
full code:
```
let groupProfile = mesiboInstance?.getProfile(addressId, groupid: groupProfiles!.getGroupId())
let gp = groupProfile?.getGroupProfile()
gp?.deleteGroup()
```
the group is not deleted.

**Comment by mesibo** [comment]
This repository is not for support.
